version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install
          command: npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Start Graph Cool Local Cluster
          command: npm run gc:local:up
      - run:
          name: Deploy to Local Cluster
          command: npm run gc:deploy:local
      # - run:
      #     name: Run tests
      #     command: docker run -it --network container:a77d5a5e2299 -v $PWD:/ node bash test.sh
